banco: 0..2
lote: 3..6
registro: 7..7
res_cnab1: 8..16 # Uso Exclusivo febraban
tipo_empresa: 17..17
num_empresa: 18..31
convenio: 33..51
agencia: 52..56
dv_agencia: 57..57
conta_corrente: 59..64
dv_conta: 70..70
dv_conta_agencia: 71..71
nome_empresa: 73..102
nome_banco: 103..132
res_cnab2: 132..141
cod_retorno: 143..143
data_geracao_arq: 144..151
hora_geracao_arq: 152..157
sequencia: 158..163
versao: 164..166
densidade: 167..171
res_banco: 172..191
res_empresa: 192..211
res_cnab3: 211..239
