banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_cnab1: 14..14
cod_movimentacao: 15..16
capital_social_empresa: 17..29 # Capital Social da Empresa     - C098
capital_socital_estabelecimento: 30..42 # Capital Social do Estabelecimento - C099
numero_empregados: 43..51 # Número de Empregados Contribuintes  - C100
total_remuneracao: 52..64 # Total da Remuneração – Contribuintes- C101
total_empregado: 65..73 #   Total de Empregados do Estabelecimento - C102
cod_cnae: 74..78 # Código CNAE Contribuinte/Pagador     - C103
tipo_entidade: 79..79 # Tipo de Entidade Sindical       - C105  - 1=Sindicato; 2=Federação; 3=Confederação; 4=M.T.E; 5=Central Sindical
cod_entidade: 80..84 # Código sindical da Entidade Sindical  - C106  -   CÓDIGO SINDICAL
tipo_arrecadacao: 85..85 # Tipo de Arrecadação “D”=Direto/”I”Indireto  - INDIRETA USADA SOMENTE PARA Federacao e confederacao
valor_pago: 86..100 #  Valor Pago pelo Pagador         - c052 -
valor_liquido: 101..115 # Valor Líquido a ser Creditado     -
valor_multa: 116..130 # Juros / Multa / Encargos        - C048
valor_outros: 131..145 # Valor de Outros Créditos        - C055
data_ocorrencia: 146..153 # Data da Ocorrência
data_efetivacao_credito: 154..161 # Data da Efetivação do Crédito     - data que o dinheiro vai cair na conta.
res_cnab_2: 162..165 # Uso Exclusivo CAIXA           - numeração que eu não faço ideia
data_debito_tarifa: 166..173 # Data do Débito da Tarifa        - está vindo brancos
cod_pagador: 174..188 # Código do Pagador no Banco        - C080
res_cnab3: 189..218 # Uso Exclusivo CAIXA           - está vindo local de pagamento ( LOTERICOS SISPL, CIP COMPENSACAO POR EXEMPLO)
res_cnab_3: 219..239 # Uso Exclusivo FEBRABAN/CNAB       - brancos
